# Pandas Finance & HR Data Analysis

## Month 5 | Week 1 Mini-Project

### Objective

Perform an end-to-end data analysis workflow using Pandas on an HR Analytics dataset.

### Workflow

1. Load the dataset
2. Inspect the data
3. Select relevant columns
4. Filter records using business conditions
5. Analyze groups using `groupby()`
6. Generate business insights
7. Perform a basic missing-value check
8. Summarize the findings

### Dataset

HR Analytics Dataset

In [59]:
import pandas as pd

In [60]:
df = pd.read_csv('../data/raw/HR_Analytics.csv')
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [61]:
df.shape

(1480, 38)

In [62]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

## 1. Load and Inspect the Dataset

The dataset is loaded using `pd.read_csv()`.

The first few rows, dataset dimensions, and column names are inspected to understand the structure of the data before analysis.

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   object
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   object
 25  OverTime                  1480 non-null   object
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
 37  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 439.5+ KB

In [64]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1480.000000,1480.000000,1480.000000,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,...,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1423.000000
mean,36.917568,801.384459,9.220270,2.910811,1.0,1031.860811,2.724324,65.845270,2.729730,2.064865,...,2.708784,80.0,0.791892,11.281757,2.797973,2.760811,7.009459,4.228378,2.182432,4.118060
std,9.128559,403.126988,8.131201,1.023796,0.0,605.955046,1.092579,20.328266,0.713007,1.105574,...,1.081995,0.0,0.850527,7.770870,1.288791,0.707024,6.117945,3.616020,3.219357,3.555484
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,493.750000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,800.000000,7.000000,3.000000,1.0,1027.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1568.250000,4.000000,83.000000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [65]:
df.dtypes

EmpID                        object
Age                           int64
AgeGroup                     object
Attrition                    object
BusinessTravel               object
DailyRate                     int64
Department                   object
DistanceFromHome              int64
Education                     int64
EducationField               object
EmployeeCount                 int64
EmployeeNumber                int64
EnvironmentSatisfaction       int64
Gender                       object
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome                 int64
SalarySlab                   object
MonthlyRate                   int64
NumCompaniesWorked            int64
Over18                       object
OverTime                     object
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
StandardHours                 int64
StockOptionLevel              int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager        float64
dtype: object

In [66]:
employee_view = df[
    [
        "EmployeeNumber",
        "Age",
        "Gender",
        "Department",
        "JobRole",
        "MonthlyIncome",
        "JobSatisfaction"
    ]
]

employee_view.head()

,EmployeeNumber,Age,Gender,Department,JobRole,MonthlyIncome,JobSatisfaction
0,405,18,Male,Research & Development,Laboratory Technician,1420,3
1,411,18,Female,Sales,Sales Representative,1200,3
2,614,18,Male,Sales,Sales Representative,1878,2
3,1012,18,Male,Research & Development,Research Scientist,1051,4
4,1156,18,Male,Research & Development,Laboratory Technician,1904,3

## 2. Selecting Relevant Columns

For analysis, only relevant employee, department, income, and satisfaction fields are selected.

Selecting specific columns makes the analysis easier to read and keeps the workflow focused on the business questions.

In [67]:
high_income = df[
    df["MonthlyIncome"] > 5000
]

high_income.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
97,RM108,25,18-25,Yes,Travel_Rarely,240,Sales,5,3,Marketing,...,4,80,0,6,1,3,6,4,0,3.0
99,RM139,25,18-25,No,Travel_Rarely,959,Sales,28,3,Life Sciences,...,4,80,0,6,3,3,2,2,2,NaN
106,RM564,25,18-25,No,Travel_Rarely,883,Sales,26,1,Medical,...,2,80,0,6,5,2,6,5,1,4.0
116,RM994,25,18-25,No,Travel_Rarely,1372,Sales,18,1,Life Sciences,...,2,80,0,6,3,2,3,2,1,2.0
119,RM1175,25,18-25,No,Travel_Frequently,772,Research & Development,2,1,Life Sciences,...,3,80,2,7,6,3,7,7,0,7.0

In [68]:
experienced_employees = df[
    (df["YearsAtCompany"] > 5) &
    (df["MonthlyIncome"] < 5000)
]

experienced_employees.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
78,RM475,24,18-25,No,Travel_Rarely,691,Research & Development,23,3,Medical,...,2,80,2,6,3,3,6,5,1,4.0
80,RM480,24,18-25,Yes,Travel_Frequently,1287,Research & Development,7,3,Life Sciences,...,4,80,1,6,4,3,6,3,1,2.0
91,RM1169,24,18-25,No,Travel_Frequently,567,Research & Development,2,1,Technical Degree,...,3,80,0,6,2,3,6,3,1,3.0
94,RM1231,24,18-25,No,Travel_Rarely,506,Research & Development,29,1,Medical,...,2,80,3,6,2,4,6,2,1,2.0
101,RM268,25,18-25,No,Non-Travel,675,Research & Development,5,2,Life Sciences,...,4,80,2,6,2,3,6,3,1,5.0

In [69]:
experienced_employees.sort_values(
    "MonthlyIncome",ascending=False
).head(10)

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
496,RM882,32,26-35,No,Travel_Frequently,1316,Research & Development,2,2,Life Sciences,...,4,80,0,10,2,3,8,7,0,7.0
382,RM1245,30,26-35,No,Travel_Frequently,1312,Research & Development,2,4,Technical Degree,...,4,80,0,10,2,3,9,7,0,7.0
1242,RM533,47,46-55,No,Travel_Rarely,703,Sales,14,4,Marketing,...,4,80,0,20,2,3,7,7,1,7.0
1359,RM318,52,46-55,Yes,Travel_Rarely,723,Research & Development,8,4,Medical,...,1,80,0,11,3,2,8,2,7,7.0
1347,RM377,51,46-55,No,Travel_Rarely,1178,Sales,14,2,Life Sciences,...,3,80,1,18,2,2,7,7,0,7.0
1058,RM282,42,36-45,No,Travel_Rarely,635,Sales,1,1,Life Sciences,...,3,80,0,20,3,3,20,16,11,6.0
1450,RM1054,57,55+,No,Travel_Rarely,405,Research & Development,1,2,Life Sciences,...,1,80,1,13,2,2,12,9,2,8.0
498,RM940,32,26-35,Yes,Travel_Rarely,1089,Research & Development,7,2,Life Sciences,...,1,80,1,10,3,3,10,4,1,1.0
577,RM1426,33,26-35,No,Travel_Rarely,501,Research & Development,15,2,Medical,...,1,80,1,10,6,3,9,7,8,1.0
1122,RM1134,43,36-45,No,Travel_Rarely,990,Research & Development,27,3,Technical Degree,...,3,80,1,8,0,3,6,4,0,2.0

## 3. Filtering and Sorting

Conditional filtering is used to identify employees matching specific business criteria.

The analysis also uses sorting to rank employees based on monthly income.

In [70]:
avg_income_by_department = (
    df.groupby("Department")["MonthlyIncome"]
      .mean()
      .sort_values(ascending=False)
)

avg_income_by_department

Department
Sales                     6966.737778
Human Resources           6654.507937
Research & Development    6280.365047
Name: MonthlyIncome, dtype: float64

In [71]:
employee_count_by_department = (
    df.groupby("Department")
      .size()
      .sort_values(ascending=False)
)

employee_count_by_department

Department
Research & Development    967
Sales                     450
Human Resources            63
dtype: int64

In [72]:
department_income_summary = (
    df.groupby("Department")["MonthlyIncome"]
      .agg(["mean", "min", "max", "count"])
)

department_income_summary

                               mean   min    max  count
Department
Human Resources         6654.507937  1555  19717     63
Research & Development  6280.365047  1009  19999    967
Sales                   6966.737778  1052  19847    450

## 4. GroupBy Analysis and Business Insights

Department-level aggregation is used to compare employee income across departments.

### Questions

- Which department has the highest average monthly income?
- Which department has the lowest average monthly income?
- How many employees are present in each department?
- How does income vary across departments?

The grouped results provide a basic view of department-level compensation patterns.

In [73]:
avg_income_by_department.idxmax()

'Sales'

In [74]:
avg_income_by_department.max()

6966.737777777777

In [75]:
avg_income_by_department.idxmin()

'Research & Development'

In [76]:
avg_income_by_department.min()

6280.365046535678

## 5. Basic Data Quality Check

Before drawing conclusions from the dataset, a first-pass check is performed for missing values.

The goal is to identify columns containing data gaps.

In [77]:
missing_values = df.isna().sum()

missing_values[missing_values > 0]

YearsWithCurrManager    57
dtype: int64

In [78]:
df.isnull().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [79]:
df.duplicated().sum()

np.int64(7)

## 6. Final Summary

This mini-project demonstrates a complete first-pass Pandas workflow using the HR Analytics dataset.

### Skills Applied

- Loading CSV data with `pd.read_csv()`
- Inspecting DataFrame structure
- Selecting relevant columns
- Filtering using Boolean conditions
- Sorting analysis results
- Grouping data with `groupby()`
- Aggregating data with `mean()`, `min()`, `max()`, and `count()`
- Checking missing values with `isna()` and `isnull()`
- Checking duplicate records

### Business Perspective

Pandas can be used to transform raw employee data into structured information that supports basic HR and compensation analysis.

### Week 1 Outcome

I can now perform a basic end-to-end data analysis workflow using Pandas on a real-world dataset.